### ISSUE TITLE
Attr no longer innherits from Node in DOM4: breaks wgxpath.NodeSet.merge

### ISSUE THREAD

**Issue by mjgp2** [google/wicked-good-xpath#40]
wgxpath.NodeSet.merge  depends upon the result of the xpath inheriting from Node, and in particular being able to compare the node order, e.g. when doing `//img/@src`

```TypeError: Cannot read property 'createRange' of undefined
    at Object.b.dom.compareNodeOrder (wgxpath.install-node.js:255:276)
    at Function.f.NodeSet.merge (wgxpath.install-node.js:281:723)
    at [object Object].f.PathExpr.evaluate (wgxpath.install-node.js:317:13)
    at [object Object].evaluate (wgxpath.install-node.js:344:370)
    at Document.e.evaluate (wgxpath.install-node.js:350:286)
```

What do you think the best solution for this is? Perhaps wrapping the Attr instance in a Node wrapper? Unfortunately the spec[1] doesn't even have a link back to the owning element (which actually seems to contradict some of the text within the section).

[1] https://www.w3.org/TR/dom/#interface-attr

**Comment by mjgp2** [comment]
I opened an issue with the W3C, I think this is a spec problem:

https://github.com/w3c/dom/issues/6

Note that the issue occurs with JSDOM which implements DOM4

**Comment by Dominator008** [comment]
We do have a wrapper for old IE browsers: https://github.com/google/wicked-good-xpath/blob/6d0f17e039321aec591918f2286d9c171d2df135/src/ieAttrWrapper.js

Looks like we'd need one for new browsers now, assuming the specs won't change.
