### ISSUE TITLE
createRange function missing with jsdom 15.2.0

### ISSUE THREAD

**Issue by mapi33** [google/wicked-good-xpath#56]
In nodejs, I use jsdom 15.2.0 to parse the html source code.
It works well for most XPaths except when the path is to an attribute, such as //div/@class.

`TypeError: Cannot read property 'createRange' of undefined
    at La (/var/www/api/node_modules/wicked-good-xpath/dist/wgxpath.install-node.js:42:35)
    at Pa (/var/www/api/node_modules/wicked-good-xpath/dist/wgxpath.install-node.js:42:645)
    at kb.a (/var/www/api/node_modules/wicked-good-xpath/dist/wgxpath.install-node.js:57:328)
    at Nb.evaluate (/var/www/api/node_modules/wicked-good-xpath/dist/wgxpath.install-node.js:73:1130)
    at Document.Pb.d.evaluate (/var/www/api/node_modules/wicked-good-xpath/dist/wgxpath.install-node.js:77:159)`

Is there any other library that is fully compatible with wgxpath? or any other workaround?

**Comment by briancullinan** [comment]
@mapi33 did you find anything? Kind of ironic the description says previous xpath implementations were buggy and outdated and now that's exactly what Google has left us with. I sometimes wonder if the rest of the world has moved on and decided this isn't how problems are solved anymore and we've been left in the dust. At least your issue is Nov 2019, I'm only 2 months behind. ;)

**Comment by ghost** [comment]
Strange, if I use an xpath like `//a/@href|(//img|//iframe|//audio)[@src]/@src` I get the error stated above. But if I use an xpath on each element like `//a` and then back in javascript iterate over `./@href` I get the expected result. Because of an API I wrote it's easy for me to update.

Looks like it was added to jsDom
https://github.com/jsdom/jsdom/commit/30bedcf62e03be5f64f1271e9753b5218c7ed9f1
